env:
  global:
      - DEPLOY_HOST=rpm.palette-software.com
      - DEPLOY_PATH=/var/palette-rpm-repo
      - DEPLOY_USER=palette-rpm

      # travis encrypt DEPLOY_PASSWORD=...
      - secure: "dKSygJzkfEdts0Jm0+0Sisv4c5I7b8DriTkOjViQ93+EXz45rSKxOX45DI7Kw7qPUCrDMEuaNK0PmSr9IMVfTF2LmDxi8vQN8rCnlnAfBTAFpptewJP+OxaxVaY2hteH+UUJ3NlRz7FQHEDjJ3aBQi9Zn0k5yNRS+2GI0dik47KH6zdD2NnI19V0SMCgVsxh2Ko4gF7tutDsApAooZtD7kEN660adduZh2I2buiKuuIO5iXPIUPcyNIknznjHx/eLh6NIdCojFdNmWBzKqCCCYQx139g9WM7Z9z287GlElDDrzL87b5+/+wVYVwxm6zs+1jqOyfy1MlluYPIDMjzFLfDqjDCDFtfIJfvGYQ2MxU3xHAdAgEnkF+3EtlY+wAmDVdmuKmaujoWZmbOOJiKI0Jzk5w0QiGW1AwtQ5ivs/kHhhDUHXCQGgz5ypa4DgdVwifCdLwcRLXHgVdqJnBSaiT8UJTt8H0ZgRJd0OMIeS9Ycq659Qcy+j397SiRHCYUxTDi9kyaKJdV9G3u0ZjzG0dQPUf11czIjVo75Z8/7BiNtQL9m8f76XIQvHSCiNv/3CU3sfJAl4kJDt3SkoxQx4EvCUt7Bd9gMRH0PrEu2LzG2A8EG8eLaCOXU85BgdVKbXbREv9zexzWPMUj8P4arUWor4UgbLq8HQCxFdNY6H0="

# install the RPM package
addons:
  apt:
    packages:
      - rpm
      # To deploy the rpms, we need to ssh into places, and we dont want to store keys for now
      - sshpass

# Put a proper version string into the version file
before_script:
  - export BUILD_TAG="$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d").$TRAVIS_BUILD_NUMBER"
  - echo "==== Setting ${BUILD_TAG} as version ===="

script:
  - export VERSION=v2.0.$TRAVIS_BUILD_NUMBER
  - ./create_rpm.sh

deploy:
  provider: script
  script: "./deploy.sh"
  skip_cleanup: true
  on:
    branch: master

notifications:
  email: false
